#!/bin/bash

echo 'Get remote translation files from web server.'
rm -rf translate-temp
mkdir -p translate-temp/res
rsync -vrz --progress linode:/www/translate.nononsenseapps.com/public_html/res/ translate-temp/res/

rm -rf translate-temp/res/values
rm -rf translate-temp/res/values-en

echo 'Isolate newest translations.'
php5 ./get-diff-translations.php

echo 'Copy new translation files to dev dir.'
cp -rf translate-temp/res ./src/main/
#echo 'Fix for traditional chinese'
#cp -rf /home/jonas/workspace/NotePad/res/values-zh-rHK/* /home/jonas/workspace/NotePad/res/values-zh-rTW/

rm -rf translate-temp
