//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.nononsenseapps.notepad.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.EditText;
import com.nononsenseapps.notepad.R.layout;

public final class TaskDetailFragment_
    extends TaskDetailFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        taskCompleted = ((CheckBox) findViewById(com.nononsenseapps.notepad.R.id.taskCompleted));
        detailsSection = ((View) findViewById(com.nononsenseapps.notepad.R.id.detailsSection));
        taskText = ((EditText) findViewById(com.nononsenseapps.notepad.R.id.taskText));
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_task_detail, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static TaskDetailFragment_.FragmentBuilder_ builder() {
        return new TaskDetailFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public TaskDetailFragment build() {
            TaskDetailFragment_ fragment_ = new TaskDetailFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
